# fly.toml app configuration file generated for weathered-dream-325 on 2023-07-31T19:58:07-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "weathered-dream-325"
primary_region = "yyz"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
