# fly.toml app configuration file generated for weathered-dream-325 on 2023-08-06T15:00:41-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "weathered-dream-325"
primary_region = "yyz"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
